'use strict';

// Danish nouns — 188 entries across 9 categories
// Fields: id, category, da, meaning, gender, definiteSg, plural, definitePl, pluralClass
// pluralClass: 'er' | 'e' | 'zero' | 'umlaut' | 'irregular' | null
// null = no meaningful plural (days, months, mass nouns) — plural/definitePl also null

const NOUNS = [

  // ── Animals ──────────────────────────────────────────────────────────────────
  { id:  1, category: 'animals', da: 'hund',        meaning: 'dog',          gender: 'en', definiteSg: 'hunden',       plural: 'hunde',       definitePl: 'hundene',       pluralClass: 'e'         },
  { id:  2, category: 'animals', da: 'kat',         meaning: 'cat',          gender: 'en', definiteSg: 'katten',       plural: 'katte',       definitePl: 'kattene',       pluralClass: 'e'         },
  { id:  3, category: 'animals', da: 'fugl',        meaning: 'bird',         gender: 'en', definiteSg: 'fuglen',       plural: 'fugle',       definitePl: 'fuglene',       pluralClass: 'e'         },
  { id:  4, category: 'animals', da: 'fisk',        meaning: 'fish',         gender: 'en', definiteSg: 'fisken',       plural: 'fisk',        definitePl: 'fiskene',       pluralClass: 'zero'      },
  { id:  5, category: 'animals', da: 'ko',          meaning: 'cow',          gender: 'en', definiteSg: 'koen',         plural: 'køer',        definitePl: 'køerne',        pluralClass: 'umlaut'    },
  { id:  6, category: 'animals', da: 'hest',        meaning: 'horse',        gender: 'en', definiteSg: 'hesten',       plural: 'heste',       definitePl: 'hestene',       pluralClass: 'e'         },
  { id:  7, category: 'animals', da: 'gris',        meaning: 'pig',          gender: 'en', definiteSg: 'grisen',       plural: 'grise',       definitePl: 'grisene',       pluralClass: 'e'         },
  { id:  8, category: 'animals', da: 'kanin',       meaning: 'rabbit',       gender: 'en', definiteSg: 'kaninen',      plural: 'kaniner',     definitePl: 'kaninerne',     pluralClass: 'er'        },
  { id:  9, category: 'animals', da: 'and',         meaning: 'duck',         gender: 'en', definiteSg: 'anden',        plural: 'ænder',       definitePl: 'ænderne',       pluralClass: 'umlaut'    },
  { id: 10, category: 'animals', da: 'mus',         meaning: 'mouse',        gender: 'en', definiteSg: 'musen',        plural: 'mus',         definitePl: 'musene',        pluralClass: 'zero'      },
  { id: 11, category: 'animals', da: 'bjørn',       meaning: 'bear',         gender: 'en', definiteSg: 'bjørnen',      plural: 'bjørne',      definitePl: 'bjørnene',      pluralClass: 'e'         },
  { id: 12, category: 'animals', da: 'løve',        meaning: 'lion',         gender: 'en', definiteSg: 'løven',        plural: 'løver',       definitePl: 'løverne',       pluralClass: 'er'        },
  { id: 13, category: 'animals', da: 'elefant',     meaning: 'elephant',     gender: 'en', definiteSg: 'elefanten',    plural: 'elefanter',   definitePl: 'elefanterne',   pluralClass: 'er'        },
  { id: 14, category: 'animals', da: 'ulv',         meaning: 'wolf',         gender: 'en', definiteSg: 'ulven',        plural: 'ulve',        definitePl: 'ulvene',        pluralClass: 'e'         },
  { id: 15, category: 'animals', da: 'ræv',         meaning: 'fox',          gender: 'en', definiteSg: 'ræven',        plural: 'ræve',        definitePl: 'rævene',        pluralClass: 'e'         },
  { id: 16, category: 'animals', da: 'abe',         meaning: 'monkey',       gender: 'en', definiteSg: 'aben',         plural: 'aber',        definitePl: 'aberne',        pluralClass: 'er'        },
  { id: 17, category: 'animals', da: 'slange',      meaning: 'snake',        gender: 'en', definiteSg: 'slangen',      plural: 'slanger',     definitePl: 'slangerne',     pluralClass: 'er'        },
  { id: 18, category: 'animals', da: 'orm',         meaning: 'worm',         gender: 'en', definiteSg: 'ormen',        plural: 'orme',        definitePl: 'ormene',        pluralClass: 'e'         },
  { id: 19, category: 'animals', da: 'bi',          meaning: 'bee',          gender: 'en', definiteSg: 'bien',         plural: 'bier',        definitePl: 'bierne',        pluralClass: 'er'        },
  { id: 20, category: 'animals', da: 'sommerfugl',  meaning: 'butterfly',    gender: 'en', definiteSg: 'sommerfuglen', plural: 'sommerfugle', definitePl: 'sommerfuglene', pluralClass: 'e'         },
  { id: 21, category: 'animals', da: 'tiger',       meaning: 'tiger',        gender: 'en', definiteSg: 'tigeren',      plural: 'tigre',       definitePl: 'tigrene',       pluralClass: 'irregular' },
  { id: 22, category: 'animals', da: 'hval',        meaning: 'whale',        gender: 'en', definiteSg: 'hvalen',       plural: 'hvaler',      definitePl: 'hvalerne',      pluralClass: 'er'        },
  { id: 23, category: 'animals', da: 'ørn',         meaning: 'eagle',        gender: 'en', definiteSg: 'ørnen',        plural: 'ørne',        definitePl: 'ørnene',        pluralClass: 'e'         },
  { id: 24, category: 'animals', da: 'krokodille',  meaning: 'crocodile',    gender: 'en', definiteSg: 'krokodillen',  plural: 'krokodiller', definitePl: 'krokodillerne', pluralClass: 'er'        },

  // ── Food & drink ─────────────────────────────────────────────────────────────
  { id: 25, category: 'food', da: 'æble',      meaning: 'apple',     gender: 'et', definiteSg: 'æblet',      plural: 'æbler',      definitePl: 'æblerne',      pluralClass: 'er'        },
  { id: 26, category: 'food', da: 'banan',     meaning: 'banana',    gender: 'en', definiteSg: 'bananen',    plural: 'bananer',    definitePl: 'bananerne',    pluralClass: 'er'        },
  { id: 27, category: 'food', da: 'tomat',     meaning: 'tomato',    gender: 'en', definiteSg: 'tomaten',    plural: 'tomater',    definitePl: 'tomaterne',    pluralClass: 'er'        },
  { id: 28, category: 'food', da: 'grøntsag',  meaning: 'vegetable', gender: 'en', definiteSg: 'grøntsagen', plural: 'grøntsager', definitePl: 'grøntsagerne', pluralClass: 'er'        },
  { id: 29, category: 'food', da: 'frugt',     meaning: 'fruit',     gender: 'en', definiteSg: 'frugten',    plural: 'frugter',    definitePl: 'frugterne',    pluralClass: 'er'        },
  { id: 30, category: 'food', da: 'kage',      meaning: 'cake',      gender: 'en', definiteSg: 'kagen',      plural: 'kager',      definitePl: 'kagerne',      pluralClass: 'er'        },
  { id: 31, category: 'food', da: 'suppe',     meaning: 'soup',      gender: 'en', definiteSg: 'suppen',     plural: 'supper',     definitePl: 'supperne',     pluralClass: 'er'        },
  { id: 32, category: 'food', da: 'kylling',   meaning: 'chicken',   gender: 'en', definiteSg: 'kyllingen',  plural: 'kyllinger',  definitePl: 'kyllingerne',  pluralClass: 'er'        },
  { id: 33, category: 'food', da: 'kartoffel', meaning: 'potato',    gender: 'en', definiteSg: 'kartoflen',  plural: 'kartofler',  definitePl: 'kartoplerne',  pluralClass: 'irregular' },
  { id: 34, category: 'food', da: 'gulerod',   meaning: 'carrot',    gender: 'en', definiteSg: 'guleroden',  plural: 'gulerødder', definitePl: 'gulerødderne', pluralClass: 'umlaut'    },
  { id: 35, category: 'food', da: 'ost',       meaning: 'cheese',    gender: 'en', definiteSg: 'osten',      plural: 'oste',       definitePl: 'ostene',       pluralClass: 'e'         },
  { id: 36, category: 'food', da: 'vin',       meaning: 'wine',      gender: 'en', definiteSg: 'vinen',      plural: 'vine',       definitePl: 'vinene',       pluralClass: 'e'         },
  { id: 37, category: 'food', da: 'laks',      meaning: 'salmon',    gender: 'en', definiteSg: 'laksen',     plural: 'laks',       definitePl: 'laksene',      pluralClass: 'zero'      },
  { id: 38, category: 'food', da: 'løg',       meaning: 'onion',     gender: 'et', definiteSg: 'løget',      plural: 'løg',        definitePl: 'løgene',       pluralClass: 'zero'      },
  { id: 39, category: 'food', da: 'brød',      meaning: 'bread',     gender: 'et', definiteSg: 'brødet',     plural: 'brød',       definitePl: 'brødene',      pluralClass: 'zero'      },
  { id: 40, category: 'food', da: 'æg',        meaning: 'egg',       gender: 'et', definiteSg: 'ægget',      plural: 'æg',         definitePl: 'æggene',       pluralClass: 'zero'      },
  { id: 41, category: 'food', da: 'øl',        meaning: 'beer',      gender: 'en', definiteSg: 'øllen',      plural: 'øl',         definitePl: 'øllene',       pluralClass: 'zero'      },
  { id: 42, category: 'food', da: 'vand',      meaning: 'water',     gender: 'et', definiteSg: 'vandet',     plural: null,         definitePl: null,           pluralClass: null        },
  { id: 43, category: 'food', da: 'mælk',      meaning: 'milk',      gender: 'en', definiteSg: 'mælken',     plural: null,         definitePl: null,           pluralClass: null        },
  { id: 44, category: 'food', da: 'kaffe',     meaning: 'coffee',    gender: 'en', definiteSg: 'kaffen',     plural: null,         definitePl: null,           pluralClass: null        },
  { id: 45, category: 'food', da: 'te',        meaning: 'tea',       gender: 'en', definiteSg: 'teen',       plural: null,         definitePl: null,           pluralClass: null        },
  { id: 46, category: 'food', da: 'smør',      meaning: 'butter',    gender: 'et', definiteSg: 'smørret',    plural: null,         definitePl: null,           pluralClass: null        },
  { id: 47, category: 'food', da: 'sukker',    meaning: 'sugar',     gender: 'et', definiteSg: 'sukkeret',   plural: null,         definitePl: null,           pluralClass: null        },
  { id: 48, category: 'food', da: 'kød',       meaning: 'meat',      gender: 'et', definiteSg: 'kødet',      plural: null,         definitePl: null,           pluralClass: null        },

  // ── Body & health ─────────────────────────────────────────────────────────────
  { id: 49, category: 'body', da: 'hoved',    meaning: 'head',      gender: 'et', definiteSg: 'hovedet',    plural: 'hoveder',   definitePl: 'hovederne',   pluralClass: 'er'        },
  { id: 50, category: 'body', da: 'øje',      meaning: 'eye',       gender: 'et', definiteSg: 'øjet',       plural: 'øjne',      definitePl: 'øjnene',      pluralClass: 'irregular' },
  { id: 51, category: 'body', da: 'øre',      meaning: 'ear',       gender: 'et', definiteSg: 'øret',       plural: 'ører',      definitePl: 'ørerne',      pluralClass: 'er'        },
  { id: 52, category: 'body', da: 'næse',     meaning: 'nose',      gender: 'en', definiteSg: 'næsen',      plural: 'næser',     definitePl: 'næserne',     pluralClass: 'er'        },
  { id: 53, category: 'body', da: 'mund',     meaning: 'mouth',     gender: 'en', definiteSg: 'munden',     plural: 'munde',     definitePl: 'mundene',     pluralClass: 'e'         },
  { id: 54, category: 'body', da: 'hånd',     meaning: 'hand',      gender: 'en', definiteSg: 'hånden',     plural: 'hænder',    definitePl: 'hænderne',    pluralClass: 'umlaut'    },
  { id: 55, category: 'body', da: 'fod',      meaning: 'foot',      gender: 'en', definiteSg: 'foden',      plural: 'fødder',    definitePl: 'fødderne',    pluralClass: 'umlaut'    },
  { id: 56, category: 'body', da: 'ben',      meaning: 'leg / bone', gender: 'et', definiteSg: 'benet',     plural: 'ben',       definitePl: 'benene',      pluralClass: 'zero'      },
  { id: 57, category: 'body', da: 'arm',      meaning: 'arm',       gender: 'en', definiteSg: 'armen',      plural: 'arme',      definitePl: 'armene',      pluralClass: 'e'         },
  { id: 58, category: 'body', da: 'mave',     meaning: 'stomach',   gender: 'en', definiteSg: 'maven',      plural: 'maver',     definitePl: 'maverne',     pluralClass: 'er'        },
  { id: 59, category: 'body', da: 'ryg',      meaning: 'back',      gender: 'en', definiteSg: 'ryggen',     plural: 'rygge',     definitePl: 'ryggene',     pluralClass: 'e'         },
  { id: 60, category: 'body', da: 'hjerte',   meaning: 'heart',     gender: 'et', definiteSg: 'hjertet',    plural: 'hjerter',   definitePl: 'hjerterne',   pluralClass: 'er'        },
  { id: 61, category: 'body', da: 'hjerne',   meaning: 'brain',     gender: 'en', definiteSg: 'hjernen',    plural: 'hjerner',   definitePl: 'hjernerne',   pluralClass: 'er'        },
  { id: 62, category: 'body', da: 'tand',     meaning: 'tooth',     gender: 'en', definiteSg: 'tanden',     plural: 'tænder',    definitePl: 'tænderne',    pluralClass: 'umlaut'    },
  { id: 63, category: 'body', da: 'finger',   meaning: 'finger',    gender: 'en', definiteSg: 'fingeren',   plural: 'fingre',    definitePl: 'fingrene',    pluralClass: 'irregular' },
  { id: 64, category: 'body', da: 'skulder',  meaning: 'shoulder',  gender: 'en', definiteSg: 'skulderen',  plural: 'skuldre',   definitePl: 'skuldrene',   pluralClass: 'irregular' },
  { id: 65, category: 'body', da: 'knæ',      meaning: 'knee',      gender: 'et', definiteSg: 'knæet',      plural: 'knæ',       definitePl: 'knæene',      pluralClass: 'zero'      },
  { id: 66, category: 'body', da: 'hals',     meaning: 'throat / neck', gender: 'en', definiteSg: 'halsen', plural: 'halse',     definitePl: 'halsene',     pluralClass: 'e'         },
  { id: 67, category: 'body', da: 'nakke',    meaning: 'nape / neck', gender: 'en', definiteSg: 'nakken',   plural: 'nakker',    definitePl: 'nakkerne',    pluralClass: 'er'        },
  { id: 68, category: 'body', da: 'pande',    meaning: 'forehead',  gender: 'en', definiteSg: 'panden',     plural: 'pander',    definitePl: 'panderne',    pluralClass: 'er'        },
  { id: 69, category: 'body', da: 'læbe',     meaning: 'lip',       gender: 'en', definiteSg: 'læben',      plural: 'læber',     definitePl: 'læberne',     pluralClass: 'er'        },
  { id: 70, category: 'body', da: 'bryst',    meaning: 'chest / breast', gender: 'et', definiteSg: 'brystet', plural: 'bryster', definitePl: 'brysterne',   pluralClass: 'er'        },

  // ── Home & objects ────────────────────────────────────────────────────────────
  { id: 71, category: 'home', da: 'stol',      meaning: 'chair',    gender: 'en', definiteSg: 'stolen',     plural: 'stole',     definitePl: 'stolene',     pluralClass: 'e'         },
  { id: 72, category: 'home', da: 'bord',      meaning: 'table',    gender: 'et', definiteSg: 'bordet',     plural: 'borde',     definitePl: 'bordene',     pluralClass: 'e'         },
  { id: 73, category: 'home', da: 'seng',      meaning: 'bed',      gender: 'en', definiteSg: 'sengen',     plural: 'senge',     definitePl: 'sengene',     pluralClass: 'e'         },
  { id: 74, category: 'home', da: 'vindue',    meaning: 'window',   gender: 'et', definiteSg: 'vinduet',    plural: 'vinduer',   definitePl: 'vinduerne',   pluralClass: 'er'        },
  { id: 75, category: 'home', da: 'dør',       meaning: 'door',     gender: 'en', definiteSg: 'døren',      plural: 'døre',      definitePl: 'dørene',      pluralClass: 'e'         },
  { id: 76, category: 'home', da: 'gulv',      meaning: 'floor',    gender: 'et', definiteSg: 'gulvet',     plural: 'gulve',     definitePl: 'gulvene',     pluralClass: 'e'         },
  { id: 77, category: 'home', da: 'loft',      meaning: 'ceiling',  gender: 'et', definiteSg: 'loftet',     plural: 'lofter',    definitePl: 'lofterne',    pluralClass: 'er'        },
  { id: 78, category: 'home', da: 'væg',       meaning: 'wall',     gender: 'en', definiteSg: 'væggen',     plural: 'vægge',     definitePl: 'væggene',     pluralClass: 'e'         },
  { id: 79, category: 'home', da: 'lampe',     meaning: 'lamp',     gender: 'en', definiteSg: 'lampen',     plural: 'lamper',    definitePl: 'lamperne',    pluralClass: 'er'        },
  { id: 80, category: 'home', da: 'bog',       meaning: 'book',     gender: 'en', definiteSg: 'bogen',      plural: 'bøger',     definitePl: 'bøgerne',     pluralClass: 'umlaut'    },
  { id: 81, category: 'home', da: 'telefon',   meaning: 'telephone', gender: 'en', definiteSg: 'telefonen', plural: 'telefoner', definitePl: 'telefonerne', pluralClass: 'er'        },
  { id: 82, category: 'home', da: 'nøgle',     meaning: 'key',      gender: 'en', definiteSg: 'nøglen',     plural: 'nøgler',    definitePl: 'nøglerne',    pluralClass: 'er'        },
  { id: 83, category: 'home', da: 'taske',     meaning: 'bag',      gender: 'en', definiteSg: 'tasken',     plural: 'tasker',    definitePl: 'taskerne',    pluralClass: 'er'        },
  { id: 84, category: 'home', da: 'glas',      meaning: 'glass',    gender: 'et', definiteSg: 'glasset',    plural: 'glas',      definitePl: 'glassene',    pluralClass: 'zero'      },
  { id: 85, category: 'home', da: 'kop',       meaning: 'cup',      gender: 'en', definiteSg: 'koppen',     plural: 'kopper',    definitePl: 'kopperne',    pluralClass: 'er'        },
  { id: 86, category: 'home', da: 'tallerken', meaning: 'plate',    gender: 'en', definiteSg: 'tallerkenen', plural: 'tallerkener', definitePl: 'tallerkenerne', pluralClass: 'er'   },
  { id: 87, category: 'home', da: 'kniv',      meaning: 'knife',    gender: 'en', definiteSg: 'kniven',     plural: 'knive',     definitePl: 'knivene',     pluralClass: 'e'         },
  { id: 88, category: 'home', da: 'gaffel',    meaning: 'fork',     gender: 'en', definiteSg: 'gaffelen',   plural: 'gafler',    definitePl: 'gaflerne',    pluralClass: 'irregular' },
  { id: 89, category: 'home', da: 'ske',       meaning: 'spoon',    gender: 'en', definiteSg: 'skeen',      plural: 'skeer',     definitePl: 'skeerne',     pluralClass: 'er'        },
  { id: 90, category: 'home', da: 'spejl',     meaning: 'mirror',   gender: 'et', definiteSg: 'spejlet',    plural: 'spejle',    definitePl: 'spejlene',    pluralClass: 'e'         },

  // ── Nature ────────────────────────────────────────────────────────────────────
  { id:  91, category: 'nature', da: 'skov',    meaning: 'forest',  gender: 'en', definiteSg: 'skoven',    plural: 'skove',    definitePl: 'skovene',    pluralClass: 'e'         },
  { id:  92, category: 'nature', da: 'sø',      meaning: 'lake',    gender: 'en', definiteSg: 'søen',      plural: 'søer',     definitePl: 'søerne',     pluralClass: 'er'        },
  { id:  93, category: 'nature', da: 'hav',     meaning: 'sea',     gender: 'et', definiteSg: 'havet',     plural: 'have',     definitePl: 'havene',     pluralClass: 'e'         },
  { id:  94, category: 'nature', da: 'bjerg',   meaning: 'mountain', gender: 'et', definiteSg: 'bjerget',  plural: 'bjerge',   definitePl: 'bjergene',   pluralClass: 'e'         },
  { id:  95, category: 'nature', da: 'flod',    meaning: 'river',   gender: 'en', definiteSg: 'floden',    plural: 'floder',   definitePl: 'floderne',   pluralClass: 'er'        },
  { id:  96, category: 'nature', da: 'træ',     meaning: 'tree',    gender: 'et', definiteSg: 'træet',     plural: 'træer',    definitePl: 'træerne',    pluralClass: 'er'        },
  { id:  97, category: 'nature', da: 'blomst',  meaning: 'flower',  gender: 'en', definiteSg: 'blomsten',  plural: 'blomster', definitePl: 'blomsterne', pluralClass: 'er'        },
  { id:  98, category: 'nature', da: 'sol',     meaning: 'sun',     gender: 'en', definiteSg: 'solen',     plural: 'sole',     definitePl: 'solene',     pluralClass: 'e'         },
  { id:  99, category: 'nature', da: 'måne',    meaning: 'moon',    gender: 'en', definiteSg: 'månen',     plural: 'måner',    definitePl: 'månerne',    pluralClass: 'er'        },
  { id: 100, category: 'nature', da: 'stjerne', meaning: 'star',    gender: 'en', definiteSg: 'stjernen',  plural: 'stjerner', definitePl: 'stjernerne', pluralClass: 'er'        },
  { id: 101, category: 'nature', da: 'sky',     meaning: 'cloud',   gender: 'en', definiteSg: 'skyen',     plural: 'skyer',    definitePl: 'skyerne',    pluralClass: 'er'        },
  { id: 102, category: 'nature', da: 'vind',    meaning: 'wind',    gender: 'en', definiteSg: 'vinden',    plural: 'vinde',    definitePl: 'vindene',    pluralClass: 'e'         },
  { id: 103, category: 'nature', da: 'sten',    meaning: 'stone',   gender: 'en', definiteSg: 'stenen',    plural: 'sten',     definitePl: 'stenene',    pluralClass: 'zero'      },
  { id: 104, category: 'nature', da: 'strand',  meaning: 'beach',   gender: 'en', definiteSg: 'stranden',  plural: 'strande',  definitePl: 'strandene',  pluralClass: 'e'         },
  { id: 105, category: 'nature', da: 'ø',       meaning: 'island',  gender: 'en', definiteSg: 'øen',       plural: 'øer',      definitePl: 'øerne',      pluralClass: 'er'        },
  { id: 106, category: 'nature', da: 'bakke',   meaning: 'hill',    gender: 'en', definiteSg: 'bakken',    plural: 'bakker',   definitePl: 'bakkerne',   pluralClass: 'er'        },
  { id: 107, category: 'nature', da: 'klippe',  meaning: 'cliff',   gender: 'en', definiteSg: 'klippen',   plural: 'klipper',  definitePl: 'klipperne',  pluralClass: 'er'        },
  { id: 108, category: 'nature', da: 'rod',     meaning: 'root',    gender: 'en', definiteSg: 'roden',     plural: 'rødder',   definitePl: 'rødderne',   pluralClass: 'umlaut'    },
  { id: 109, category: 'nature', da: 'gren',    meaning: 'branch',  gender: 'en', definiteSg: 'grenen',    plural: 'grene',    definitePl: 'grenene',    pluralClass: 'e'         },
  { id: 110, category: 'nature', da: 'sne',     meaning: 'snow',    gender: 'en', definiteSg: 'sneen',     plural: null,       definitePl: null,         pluralClass: null        },

  // ── People & relationships ────────────────────────────────────────────────────
  { id: 111, category: 'people', da: 'mand',        meaning: 'man',              gender: 'en', definiteSg: 'manden',       plural: 'mænd',      definitePl: 'mændene',      pluralClass: 'umlaut'    },
  { id: 112, category: 'people', da: 'kvinde',      meaning: 'woman',            gender: 'en', definiteSg: 'kvinden',      plural: 'kvinder',   definitePl: 'kvinderne',    pluralClass: 'er'        },
  { id: 113, category: 'people', da: 'barn',        meaning: 'child',            gender: 'et', definiteSg: 'barnet',       plural: 'børn',      definitePl: 'børnene',      pluralClass: 'umlaut'    },
  { id: 114, category: 'people', da: 'dreng',       meaning: 'boy',              gender: 'en', definiteSg: 'drengen',      plural: 'drenge',    definitePl: 'drengene',     pluralClass: 'e'         },
  { id: 115, category: 'people', da: 'pige',        meaning: 'girl',             gender: 'en', definiteSg: 'pigen',        plural: 'piger',     definitePl: 'pigerne',      pluralClass: 'er'        },
  { id: 116, category: 'people', da: 'mor',         meaning: 'mother',           gender: 'en', definiteSg: 'moren',        plural: 'mødre',     definitePl: 'mødrene',      pluralClass: 'umlaut'    },
  { id: 117, category: 'people', da: 'far',         meaning: 'father',           gender: 'en', definiteSg: 'faren',        plural: 'fædre',     definitePl: 'fædrene',      pluralClass: 'umlaut'    },
  { id: 118, category: 'people', da: 'søster',      meaning: 'sister',           gender: 'en', definiteSg: 'søsteren',     plural: 'søstre',    definitePl: 'søstrene',     pluralClass: 'irregular' },
  { id: 119, category: 'people', da: 'bror',        meaning: 'brother',          gender: 'en', definiteSg: 'broren',       plural: 'brødre',    definitePl: 'brødrene',     pluralClass: 'umlaut'    },
  { id: 120, category: 'people', da: 'ven',         meaning: 'friend',           gender: 'en', definiteSg: 'vennen',       plural: 'venner',    definitePl: 'vennerne',     pluralClass: 'er'        },
  { id: 121, category: 'people', da: 'familie',     meaning: 'family',           gender: 'en', definiteSg: 'familien',     plural: 'familier',  definitePl: 'familierne',   pluralClass: 'er'        },
  { id: 122, category: 'people', da: 'kæreste',     meaning: 'boyfriend / girlfriend', gender: 'en', definiteSg: 'kæresten', plural: 'kærester', definitePl: 'kæresterne',  pluralClass: 'er'        },
  { id: 123, category: 'people', da: 'nabo',        meaning: 'neighbour',        gender: 'en', definiteSg: 'naboen',       plural: 'naboer',    definitePl: 'naboerne',     pluralClass: 'er'        },
  { id: 124, category: 'people', da: 'kollega',     meaning: 'colleague',        gender: 'en', definiteSg: 'kollegaen',    plural: 'kollegaer', definitePl: 'kollegaerne',  pluralClass: 'er'        },
  { id: 125, category: 'people', da: 'lærer',       meaning: 'teacher',          gender: 'en', definiteSg: 'læreren',      plural: 'lærere',    definitePl: 'lærerne',      pluralClass: 'irregular' },
  { id: 126, category: 'people', da: 'læge',        meaning: 'doctor',           gender: 'en', definiteSg: 'lægen',        plural: 'læger',     definitePl: 'lægerne',      pluralClass: 'er'        },
  { id: 127, category: 'people', da: 'person',      meaning: 'person',           gender: 'en', definiteSg: 'personen',     plural: 'personer',  definitePl: 'personerne',   pluralClass: 'er'        },
  { id: 128, category: 'people', da: 'bedstemor',   meaning: 'grandmother',      gender: 'en', definiteSg: 'bedstemoren',  plural: 'bedstemødre', definitePl: 'bedstemødrene', pluralClass: 'umlaut' },

  // ── Work & places ─────────────────────────────────────────────────────────────
  { id: 129, category: 'work', da: 'arbejde',   meaning: 'work / job',  gender: 'et', definiteSg: 'arbejdet',   plural: 'arbejder',   definitePl: 'arbejderne',   pluralClass: 'er'        },
  { id: 130, category: 'work', da: 'kontor',    meaning: 'office',      gender: 'et', definiteSg: 'kontoret',   plural: 'kontorer',   definitePl: 'kontorerne',   pluralClass: 'er'        },
  { id: 131, category: 'work', da: 'skole',     meaning: 'school',      gender: 'en', definiteSg: 'skolen',     plural: 'skoler',     definitePl: 'skolerne',     pluralClass: 'er'        },
  { id: 132, category: 'work', da: 'hospital',  meaning: 'hospital',    gender: 'et', definiteSg: 'hospitalet', plural: 'hospitaler', definitePl: 'hospitalerne', pluralClass: 'er'        },
  { id: 133, category: 'work', da: 'butik',     meaning: 'shop',        gender: 'en', definiteSg: 'butikken',   plural: 'butikker',   definitePl: 'butikkerne',   pluralClass: 'er'        },
  { id: 134, category: 'work', da: 'restaurant', meaning: 'restaurant', gender: 'en', definiteSg: 'restauranten', plural: 'restauranter', definitePl: 'restauranterne', pluralClass: 'er'   },
  { id: 135, category: 'work', da: 'hotel',     meaning: 'hotel',       gender: 'et', definiteSg: 'hotellet',   plural: 'hoteller',   definitePl: 'hotellerne',   pluralClass: 'er'        },
  { id: 136, category: 'work', da: 'by',        meaning: 'city / town', gender: 'en', definiteSg: 'byen',       plural: 'byer',       definitePl: 'byerne',       pluralClass: 'er'        },
  { id: 137, category: 'work', da: 'land',      meaning: 'country',     gender: 'et', definiteSg: 'landet',     plural: 'lande',      definitePl: 'landene',      pluralClass: 'e'         },
  { id: 138, category: 'work', da: 'vej',       meaning: 'road',        gender: 'en', definiteSg: 'vejen',      plural: 'veje',       definitePl: 'vejene',       pluralClass: 'e'         },
  { id: 139, category: 'work', da: 'gade',      meaning: 'street',      gender: 'en', definiteSg: 'gaden',      plural: 'gader',      definitePl: 'gaderne',      pluralClass: 'er'        },
  { id: 140, category: 'work', da: 'hus',       meaning: 'house',       gender: 'et', definiteSg: 'huset',      plural: 'huse',       definitePl: 'husene',       pluralClass: 'e'         },
  { id: 141, category: 'work', da: 'lejlighed', meaning: 'apartment',   gender: 'en', definiteSg: 'lejligheden', plural: 'lejligheder', definitePl: 'lejlighederne', pluralClass: 'er'      },
  { id: 142, category: 'work', da: 'park',      meaning: 'park',        gender: 'en', definiteSg: 'parken',     plural: 'parker',     definitePl: 'parkerne',     pluralClass: 'er'        },
  { id: 143, category: 'work', da: 'biograf',   meaning: 'cinema',      gender: 'en', definiteSg: 'biografen',  plural: 'biografer',  definitePl: 'biograferne',  pluralClass: 'er'        },
  { id: 144, category: 'work', da: 'kirke',     meaning: 'church',      gender: 'en', definiteSg: 'kirken',     plural: 'kirker',     definitePl: 'kirkerne',     pluralClass: 'er'        },
  { id: 145, category: 'work', da: 'museum',    meaning: 'museum',      gender: 'et', definiteSg: 'museet',     plural: 'museer',     definitePl: 'museerne',     pluralClass: 'irregular' },
  { id: 146, category: 'work', da: 'station',   meaning: 'station',     gender: 'en', definiteSg: 'stationen',  plural: 'stationer',  definitePl: 'stationerne',  pluralClass: 'er'        },
  { id: 147, category: 'work', da: 'lufthavn',  meaning: 'airport',     gender: 'en', definiteSg: 'lufthavnen', plural: 'lufthavne',  definitePl: 'lufthavnene',  pluralClass: 'e'         },
  { id: 148, category: 'work', da: 'bibliotek', meaning: 'library',     gender: 'et', definiteSg: 'biblioteket', plural: 'biblioteker', definitePl: 'bibliotekerne', pluralClass: 'er'      },

  // ── Time & calendar ───────────────────────────────────────────────────────────
  { id: 149, category: 'time', da: 'dag',        meaning: 'day',       gender: 'en', definiteSg: 'dagen',      plural: 'dage',      definitePl: 'dagene',      pluralClass: 'e'         },
  { id: 150, category: 'time', da: 'uge',        meaning: 'week',      gender: 'en', definiteSg: 'ugen',       plural: 'uger',      definitePl: 'ugerne',      pluralClass: 'er'        },
  { id: 151, category: 'time', da: 'måned',      meaning: 'month',     gender: 'en', definiteSg: 'måneden',    plural: 'måneder',   definitePl: 'månederne',   pluralClass: 'er'        },
  { id: 152, category: 'time', da: 'år',         meaning: 'year',      gender: 'et', definiteSg: 'året',       plural: 'år',        definitePl: 'årene',       pluralClass: 'zero'      },
  { id: 153, category: 'time', da: 'time',       meaning: 'hour',      gender: 'en', definiteSg: 'timen',      plural: 'timer',     definitePl: 'timerne',     pluralClass: 'er'        },
  { id: 154, category: 'time', da: 'minut',      meaning: 'minute',    gender: 'et', definiteSg: 'minuttet',   plural: 'minutter',  definitePl: 'minutterne',  pluralClass: 'er'        },
  { id: 155, category: 'time', da: 'sekund',     meaning: 'second',    gender: 'et', definiteSg: 'sekundet',   plural: 'sekunder',  definitePl: 'sekunderne',  pluralClass: 'er'        },
  { id: 156, category: 'time', da: 'morgen',     meaning: 'morning',   gender: 'en', definiteSg: 'morgenen',   plural: 'morgener',  definitePl: 'morgenerne',  pluralClass: 'er'        },
  { id: 157, category: 'time', da: 'aften',      meaning: 'evening',   gender: 'en', definiteSg: 'aftenen',    plural: 'aftener',   definitePl: 'aftenerne',   pluralClass: 'er'        },
  { id: 158, category: 'time', da: 'nat',        meaning: 'night',     gender: 'en', definiteSg: 'natten',     plural: 'nætter',    definitePl: 'nætterne',    pluralClass: 'umlaut'    },
  { id: 159, category: 'time', da: 'sommer',     meaning: 'summer',    gender: 'en', definiteSg: 'sommeren',   plural: 'somre',     definitePl: 'somrene',     pluralClass: 'irregular' },
  { id: 160, category: 'time', da: 'vinter',     meaning: 'winter',    gender: 'en', definiteSg: 'vinteren',   plural: 'vintre',    definitePl: 'vintrene',    pluralClass: 'irregular' },
  { id: 161, category: 'time', da: 'forår',      meaning: 'spring',    gender: 'et', definiteSg: 'foråret',    plural: 'forår',     definitePl: 'forårene',    pluralClass: 'zero'      },
  { id: 162, category: 'time', da: 'efterår',    meaning: 'autumn',    gender: 'et', definiteSg: 'efteråret',  plural: 'efterår',   definitePl: 'efterårene',  pluralClass: 'zero'      },
  { id: 163, category: 'time', da: 'fødselsdag', meaning: 'birthday',  gender: 'en', definiteSg: 'fødselsdagen', plural: 'fødselsdage', definitePl: 'fødselsdagene', pluralClass: 'e'   },
  { id: 164, category: 'time', da: 'ferie',      meaning: 'holiday / vacation', gender: 'en', definiteSg: 'ferien', plural: 'ferier', definitePl: 'ferierne',  pluralClass: 'er'        },
  { id: 165, category: 'time', da: 'mandag',     meaning: 'Monday',    gender: 'en', definiteSg: 'mandagen',   plural: null,        definitePl: null,          pluralClass: null        },
  { id: 166, category: 'time', da: 'fredag',     meaning: 'Friday',    gender: 'en', definiteSg: 'fredagen',   plural: null,        definitePl: null,          pluralClass: null        },
  { id: 167, category: 'time', da: 'januar',     meaning: 'January',   gender: 'en', definiteSg: 'januaren',   plural: null,        definitePl: null,          pluralClass: null        },
  { id: 168, category: 'time', da: 'juli',       meaning: 'July',      gender: 'en', definiteSg: 'julien',     plural: null,        definitePl: null,          pluralClass: null        },

  // ── Abstract & common ─────────────────────────────────────────────────────────
  { id: 169, category: 'abstract', da: 'tid',         meaning: 'time',        gender: 'en', definiteSg: 'tiden',        plural: 'tider',      definitePl: 'tiderne',       pluralClass: 'er'        },
  { id: 170, category: 'abstract', da: 'sted',        meaning: 'place',       gender: 'et', definiteSg: 'stedet',       plural: 'steder',     definitePl: 'stederne',      pluralClass: 'er'        },
  { id: 171, category: 'abstract', da: 'ting',        meaning: 'thing',       gender: 'en', definiteSg: 'tingen',       plural: 'ting',       definitePl: 'tingene',       pluralClass: 'zero'      },
  { id: 172, category: 'abstract', da: 'ord',         meaning: 'word',        gender: 'et', definiteSg: 'ordet',        plural: 'ord',        definitePl: 'ordene',        pluralClass: 'zero'      },
  { id: 173, category: 'abstract', da: 'svar',        meaning: 'answer',      gender: 'et', definiteSg: 'svaret',       plural: 'svar',       definitePl: 'svarene',       pluralClass: 'zero'      },
  { id: 174, category: 'abstract', da: 'spørgsmål',   meaning: 'question',    gender: 'et', definiteSg: 'spørgsmålet',  plural: 'spørgsmål',  definitePl: 'spørgsmålene',  pluralClass: 'zero'      },
  { id: 175, category: 'abstract', da: 'problem',     meaning: 'problem',     gender: 'et', definiteSg: 'problemet',    plural: 'problemer',  definitePl: 'problemerne',   pluralClass: 'er'        },
  { id: 176, category: 'abstract', da: 'løsning',     meaning: 'solution',    gender: 'en', definiteSg: 'løsningen',    plural: 'løsninger',  definitePl: 'løsningerne',   pluralClass: 'er'        },
  { id: 177, category: 'abstract', da: 'idé',         meaning: 'idea',        gender: 'en', definiteSg: 'idéen',        plural: 'idéer',      definitePl: 'idéerne',       pluralClass: 'er'        },
  { id: 178, category: 'abstract', da: 'plan',        meaning: 'plan',        gender: 'en', definiteSg: 'planen',       plural: 'planer',     definitePl: 'planerne',      pluralClass: 'er'        },
  { id: 179, category: 'abstract', da: 'resultat',    meaning: 'result',      gender: 'et', definiteSg: 'resultatet',   plural: 'resultater', definitePl: 'resultaterne',  pluralClass: 'er'        },
  { id: 180, category: 'abstract', da: 'mulighed',    meaning: 'possibility', gender: 'en', definiteSg: 'muligheden',   plural: 'muligheder', definitePl: 'mulighederne',  pluralClass: 'er'        },
  { id: 181, category: 'abstract', da: 'grund',       meaning: 'reason',      gender: 'en', definiteSg: 'grunden',      plural: 'grunde',     definitePl: 'grundene',      pluralClass: 'e'         },
  { id: 182, category: 'abstract', da: 'mening',      meaning: 'opinion / meaning', gender: 'en', definiteSg: 'meningen', plural: 'meninger', definitePl: 'meningerne',  pluralClass: 'er'        },
  { id: 183, category: 'abstract', da: 'følelse',     meaning: 'feeling',     gender: 'en', definiteSg: 'følelsen',     plural: 'følelser',   definitePl: 'følelserne',    pluralClass: 'er'        },
  { id: 184, category: 'abstract', da: 'tanke',       meaning: 'thought',     gender: 'en', definiteSg: 'tanken',       plural: 'tanker',     definitePl: 'tankerne',      pluralClass: 'er'        },
  { id: 185, category: 'abstract', da: 'liv',         meaning: 'life',        gender: 'et', definiteSg: 'livet',        plural: 'liv',        definitePl: 'livene',        pluralClass: 'zero'      },
  { id: 186, category: 'abstract', da: 'verden',      meaning: 'world',       gender: 'en', definiteSg: 'verdenen',     plural: 'verdener',   definitePl: 'verdenerne',    pluralClass: 'er'        },
  { id: 187, category: 'abstract', da: 'historie',    meaning: 'history / story', gender: 'en', definiteSg: 'historien', plural: 'historier', definitePl: 'historierne',  pluralClass: 'er'        },
  { id: 188, category: 'abstract', da: 'navn',        meaning: 'name',        gender: 'et', definiteSg: 'navnet',       plural: 'navne',      definitePl: 'navnene',       pluralClass: 'e'         },

];
